= GitHub app authentication guide

This guide is targeted to users who want to use a link:https://developer.github.com/v3/apps/[GitHub app]
to authenticate to Jenkins.

== Why?

- the link:https://developer.github.com/apps/building-github-apps/understanding-rate-limits-for-github-apps/[rate limit]
for a GitHub app scales with your organization size, whereas a user based token has a limit of 5000 regardless of
how many repositories you have,
- for organization's that have 2fa enforced - no need to manage 2fa tokens for a 'bot' user
- to improve and tighten security: the Jenkins GitHub app requires a minimum, controlled set of privileges compared to a service user and its personal access token which has a much wider set of privileges

== Getting started

Before you get started make sure you have the required permissions:

=== GitHub

You'll need the permission to create a GitHub app, if you're creating it on a personal account then you can skip this section,
otherwise:

- organization owner

or

- permission to manage GitHub apps has been
link:https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/adding-github-app-managers-in-your-organization[delegated to you].

=== Jenkins

You'll need the permission to create a new credential and update job configuration, the specific permissions are:

- Credentials/Create
- Job/Configure

== Creating the GitHub app

link:https://docs.github.com/en/developers/apps/creating-a-github-app[Follow the GitHub guide for creating an app]

The only fields you need to fill out (currently) are:

- Github App name - i.e. `Jenkins - <team name>`
- Homepage URL - your company domain or a github repository
- Webhook URL - your jenkins instance, i.e. `https://<jenkins-host>/github-webhook/`

Permissions this plugin uses:

- Commit statuses - Read and Write
- Contents: Read-only (to read the `Jenkinsfile` and the repository content during `git fetch`). You may need "Read & write" to update the repository such as tagging releases
- Metadata: Read-only
- Pull requests: Read-only

Under _Subscribe to events_, enable all events.

Click 'Create GitHub app'

You now need to generate a private key authenticating to the GitHub app

Click the 'generate a private key' option.

After a couple of seconds the key will be downloaded to your downloads folder.

Now you need to convert the key into a different format that Jenkins can use:

[source,shell]
----
openssl pkcs8 -topk8 -inform PEM -outform PEM -in key-in-your-downloads-folder.pem -out converted-github-app.pem -nocrypt
----

== Install the GitHub app

- From the install app section of newly created app, install the app to your organization.

== Adding the Jenkins credential

=== UI

- From the Jenkins main page click 'Credentials'
- Pick your credential store, normally `(global)`
- Click 'Add credentials'

Fill out the form:

- Kind: GitHub app
- ID: i.e. github-app-<team-name>
- App ID: the github app ID, it can be found in the 'About' section of your GitHub app in the general tab.
- API endpoint (optional, only required for GitHub enterprise this will only show up if a GitHub enterprise server is configured).
- Key: click add, paste the contents of the converted private key
- Advanced: (optional):
  * Repository access strategy: Controls what GitHub repositories will be accessible to these credentials in untrusted contexts (see below for details)
  * Default permissions strategy: Controls what GitHub permissions will be accessible to these credentials in untrusted contexts (see below for details)
- Click OK

=== link:https://github.com/jenkinsci/configuration-as-code-plugin[Configuration as Code Plugin]

[source,yaml]
----
credentials:
  system:
    domainCredentials:
      - credentials:
        - gitHubApp:
            appID: "1111"
            description: "GitHub app"
            id: "github-app"
            # apiUri: https://my-custom-github-enterprise.com/api/v3 # optional only required for GitHub enterprise
            privateKey: "${GITHUB_APP_KEY}"
----

== Configuring the github organization folder

See the link:https://docs.cloudbees.com/docs/cloudbees-ci/latest/cloud-admin-guide/github-branch-source-plugin[main documentation]
for how to create a GitHub folder.

- Load the folders configuration page
- Select the GitHub app credentials in the 'Credentials field drop down
- If you are using GitHub enterprise make sure the API url is set to your server,
(note you currently need to set the API url on both the credential and the job).

After selecting the credential you should see:

[quote]
----
GHApp verified, remaining rate limit: 5000
----

- Click save
- Click 'Scan organization now'
- Click 'Scan organisation log'

Verify at the bottom of the scan log it says:

[quote]
----
Finished: SUCCESS
----

=== Enhancing security using repository access strategies and default permissions strategies

GitHub App Credentials offer advanced configuration options that can provide additional security in some scenarios.
In particular, when GitHub App Credentials are used by an Organization Folder or Multibranch Pipeline, these strategies may dynamically restrict the accessible repositories and permissions available to the credentials when they are accessed in untrusted contexts, such as when they are accessed by a `withCredentials` step in one of the individual Pipeline jobs.
See link:https://www.jenkins.io/doc/book/security/securing-org-folders-and-multibranch-pipelines/[this documentation] for additional information on why it may be beneficial to limit credentials in this way.
These strategies do not apply when using the credentials in trusted contexts, such as during organization folder scans and branch indexing.
Note also that Jenkins users who have Job/Configure permission in a context where the credentials are available are considered trusted and can bypass these strategies by configuring jobs as desired.
In trusted contexts, the generated access tokens will have the same access as configured for the app installation in GitHub.

The following repository access strategies are available:

* **Infer owner and allow access to all owned repositories** (default)
    ** The credentials may only be used in contexts where a GitHub organization can be inferred, such as Organization Folders and Multibranch Pipelines
    ** The access tokens generated in untrusted contexts will be able to access all repositories in the inferred GitHub organization that are accessible to the GitHub App installation.
* **Infer accessible repository**
    ** The credentials may only be used in contexts where a GitHub organization and repository can be inferred, such as Organization Folders and Multibranch Pipelines
    ** The access tokens generated in untrusted contexts will only be able to access the inferred repository
* **Specify accessible repositories**
    ** The access tokens generated in untrusted contexts will be able to access the repositories specified statically in the credential configuration
    ** If the GitHub app is installed in a single organization, the owner field may be left blank empty, in which case that organization will be accessed automatically
    ** Leaving the repositories field empty will result in all repositories accessible to the configured owner being accessible

The following default permissions strategies are available:

* **Read-only access to repository contents**
    ** The access tokens generated in untrusted contexts will only be able to read the repository contents
* **Read and write access to repository contents**
    ** The access tokens generated in untrusted contexts will only be able to read and write the repository contents
* **All permissions available to the app installation** (default)
    ** The access tokens generated in untrusted contexts will have the same permissions as the app installation in GitHub

==== Repository access strategies limitations

===== Jobs using plain Git

The inference-based modes for GitHub App Credentials are supported for Organization Folders and Multibranch Pipelines only. There are not supported in other contexts using plain Git such as:
* Standalone Pipeline jobs using "Pipeline script from SCM"
* Freestyle jobs

===== Pipeline libraries

Note that Pipeline libraries do not support inference, and will instead be inferred to have the same owner as the main SCM for the build itself. If the library's SCM is in a different repository than the build, you will not be able to use "Infer accessible repository" for the credentials used by the library.

If the library's SCM is in a different GitHub organization than the SCM for the build, you will also not be able to use "Infer owner and allow access to all owned repositories". To avoid these issues, you can configure the Pipeline library to use a credential with the "Specify accessible repositories" mode that allows access to the repository that contains the library itself.

This means that the library will be inaccessible if you use an inference-based repository access strategy which only provides access to a single contextually-inferred repository, or if the Pipeline library is in a different GitHub organization than the repository being built.

For now, in this case, you either need to use a less restrictive strategy for the GitHub App credential, such as "Infer owner and allow access to all owned repositories" (only works if the library is only used from jobs inside of Organization Folders and Multibranch Pipelines), or "Specify accessible repositories", which works in all cases. If desired, you can also create a second credential specifically for the library, which uses "Specify accessible repositories" to restrict access to only the library's repository and configures the "Default permissions strategy" to only allow read access.

==== Backwards compatibility

[IMPORTANT]
The new configuration options are not fully backwards compatible.

For existing GitHub App credentials which do not have the owner field set, the migration to the new format is not fully compatible. These credentials migrate to the “Infer owner and allow access to all owned repositories” mode described in the documentation, which means that they will only work in contexts where the owner can be inferred, such as Organization Folders and Multibranch Pipelines.

If you are using the credentials in a context where inference is not supported, you will need to reconfigure these credentials to use the “Specify accessible repositories” mode instead, specifying the appropriate owner (or leaving it blank if the app is installed in a single GitHub organization).

=== Help?

Raise an issue on link:https://issues.jenkins-ci.org/[Jenkins jira]
setting the 'component' to be `github-branch-source-plugin`
