= GitHub app authentication guide

This guide is targeted to users who want to use a link:https://developer.github.com/v3/apps/[GitHub app]
to authenticate to Jenkins.

== Why?

- the link:https://developer.github.com/apps/building-github-apps/understanding-rate-limits-for-github-apps/[rate limit]
for a GitHub app scales with your organization size, whereas a user based token has a limit of 5000 regardless of
how many repositories you have,
- for organization's that have 2fa enforced - no need to manage 2fa tokens for a 'bot' user

== Getting started

Before you get started make sure you have the required permissions:

=== GitHub

You'll need the permission to create a GitHub app, if you're creating it on a personal account then you can skip this section,
otherwise:

- organization owner

or

- permission to manage GitHub apps has been
link:https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/adding-github-app-managers-in-your-organization[delegated to you].

=== Jenkins

You'll need the permission to create a new credential and update job configuration, the specific permissions are:

- Credentials/Create
- Job/Configure

== Creating the GitHub app

link:https://developer.github.com/apps/building-github-apps/creating-a-github-app/[Follow the GitHub guide for creating an app]

The only fields you need to fill out (currently) are:

- Github App name - i.e. `Jenkins - <team name>`
- Homepage URL - your company domain or a github repository
- Webhook URL - your jenkins instance, i.e. `https://<jenkins-host>/github-webhook/`

Permissions this plugin uses:

- Commit statuses - Read and Write
- Contents: Read-only (to read the Jenkinsfile)
- Metadata: Read-only
- Pull requests: Read-only
- Webhooks (optional) - If you want the plugin to manage webhooks for you, Read and Write


Click 'Create GitHub app'

You now need to generate a private key authenticating to the GitHub app

Click the 'generate a private key' option.

After a couple of seconds the key will be downloaded to your downloads folder.

Now you need to convert the key into a different format that Jenkins can use:

[source,shell]
----
openssl pkcs8 -topk8 -inform PEM -outform PEM -in key-in-your-downloads-folder.pem -out converted-github-app.pem -nocrypt
----

== Adding the Jenkins credential

- From the Jenkins main page click 'Credentials'
- Pick your credential store, normally `(global)`
- Click 'Add credentials'

Fill out the form:

- Kind: SSH username with private key
- ID: i.e. github-app-<team-name>
- Username: the github app ID, it can be found in the 'About' section of your GitHub app in the general tab.
- Private key: enter directly, paste the contents of the converted private key
- Passphrase: do not fill this field, it will be ignored
- Click OK

== Configuring the github organization folder

See the link:https://docs.cloudbees.com/docs/admin-resources/latest/plugins/github-branch-source[main documentation]
for how to create a GitHub folder.

- Load the folders configuration page
- Select the GitHub app credentials in the 'Credentials field drop down

After selecting the credential you should see:

[quote]
----
GHApp verified, remaining rate limit: 5000
----

- Click save
- Click 'Scan organization now'
- Click 'Scan organisation log'

Verify at the bottom of the scan log it says:

[quote]
----
Finished: SUCCESS
----

=== Help?

Raise an issue on link:https://issues.jenkins-ci.org/[Jenkins jira]
setting the 'component' to be `github-brance-source-plugin`
